### ISSUE TITLE
problem during installation

### ISSUE THREAD

**Issue by Hananebh** [holab-hku/DCATS#8]
Hello, thank you for the package I would like to install the package on my machine but I have errors regardless of how I try to install it, devtools::install_github("holab-hku/DCATS", build_vignettes = TRUE)
Downloading GitHub repo holab-hku/DCATS@HEAD
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/5k/80_80qr56p38cvfsvbvml2t40000gn/T/Rtmp9Sr6Xh/remotes27e8476486d6/holab-hku-DCATS-e1d2438/DESCRIPTION’ ...
─  preparing ‘DCATS’:
E  checking DESCRIPTION meta-information ...
   Champ Author@R mal orthographié :
     <text>:4:5: symbole inattendu
   3:            comment = c(ORCID = "0000-0002-7780-2461"))
   4:     person
          ^
   
   Voyez la section 'The DESCRIPTION file' du manuel 'Writing R
   Extensions'.
Erreur : Failed to install 'DCATS' from GitHub:
  ! System command 'R' failed 
and BiocManager::install("DCTAS")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.17 (BiocManager 1.30.21), R 4.3.1 (2023-06-16)
Installing package(s) 'DCTAS'
Message d'avis :
le package ‘DCTAS’ n'est pas disponible for this version of R
thank you

**Comment by linxy29** [comment]
Hello @Hananebh ,

Thank you for raising the issue. This bug should be fixed now. Please try again and let me know if you come across any problems.  

Xinyi

**Comment by Hananebh** [comment]
hello @linxy29
Thank you for your answer, I was able to install the package with  devtools::install_github("holab-hku/DCATS") (it still doesn't work with BiocManager::install("DCTAS"))
Thank you
hanane

**Comment by Hananebh** [comment]
hello @linxy29
thank you again for the package but I need please an example of interpretation of results or plot to show the difference between the two conditions? thank you again

**Comment by YingxinLin** [comment]
Hi,

I think there is a typo in the README file of the line
```
BiocManager::install("DCTAS")
```

It should be `BiocManager::install("DCATS")`. 

Also, currently this package is still in devel? So it requires an extra line to install at the moment... 

```
# The following initializes usage of Bioc devel
BiocManager::install(version='devel')

BiocManager::install("DCATS")
```

Best wishes,
Yingxin

**Comment by linxy29** [comment]
Thank you Yingxin @YingxinLin !

The README file was updated accordingly.
